### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by ducviet00** [hclhkbu/GaussianK-SGD#1]
from datasets import DatasetHDF5
ModuleNotFoundError: No module named 'datasets'

I cannot find module datasets in your code or pip package.

**Comment by shyhuai** [comment]
Please find ``datasets.py'' here: https://github.com/shyhuai/GaussianK-SGD/blob/master/datasets.py. This is a customized class for loading the ImageNet dataset with HDF5 format to accelerate I/O speed. 

So if you don't have an HDF5 file of the ImageNet dataset, you can choose the default data loading mechanism of ImageNet by changing lines https://github.com/hclhkbu/GaussianK-SGD/blob/master/dl_trainer.py#L307 and https://github.com/hclhkbu/GaussianK-SGD/blob/master/dl_trainer.py#L308 to https://github.com/hclhkbu/GaussianK-SGD/blob/master/dl_trainer.py#L306. Similar to the validation set in line https://github.com/hclhkbu/GaussianK-SGD/blob/master/dl_trainer.py#L330.
